Entity/Manual.php
<?php

namespace Itsur\AeiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Itsur\AeiBundle\Entity\Area;

/**
 * Itsur\AeiBundle\Entity\Manual
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Itsur\AeiBundle\Repository\ManualRepository")
 */
class Manual
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string $clave
     *
     * @ORM\Column(name="clave", type="string", length=10)
     */
    protected $clave;

    /**
     * @var string $nombre
     *
     * @ORM\Column(name="nombre", type="string", length=255)
     */
    protected $nombre;
    

    /**
     * @var integer $puntaje
     *
     * @ORM\Column(name="puntuaje", type="integer", nullable="true")
     */
    protected $puntaje;
    
    /**
     * @var integer $puntajeSeleccion
     *
     * @ORM\Column(name="puntuajeSeleccion", type="integer", nullable="true")
     */
    protected $puntajeSeleccion;
    
    /**
     * @var integer $puntajeDiagnostico
     *
     * @ORM\Column(name="puntajeDiagnostico", type="decimal", nullable="true")
     */
    protected $puntajeDiagnostico;
    
    
    /**
     *
     * @ORM\OneToMany(targetEntity="Area", mappedBy="manual")
     * @ORM\OrderBy({"id" = "ASC"})
     */
    protected $areas;
    
    public function __construct()
    {
        $this->areas = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set clave
     *
     * @param string $clave
     */
    public function setClave($clave)
    {
        $this->clave = $clave;
    }

    /**
     * Get clave
     *
     * @return string 
     */
    public function getClave()
    {
        return $this->clave;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }
    
    /**
     * Set puntaje
     *
     * @param integer $puntaje
     */
    public function setPuntaje($puntaje)
    {
        $this->puntaje = $puntaje;
    }

    /**
     * Get puntaje
     *
     * @return integer
     */
    public function getPuntaje()
    {
        return $this->puntaje;
    }
    
    /**
     * Set puntajeSeleccion
     *
     * @param integer $puntaje
     */
    public function setPuntajeSeleccion($puntajeSeleccion)
    {
        $this->puntajeSeleccion = $puntajeSeleccion;
    }

    /**
     * Get puntajeSeleccion
     *
     * @return integer
     */
    public function getPuntajeSeleccion()
    {
        return $this->puntajeSeleccion;
    }
    

    /**
     * Set puntajeDiagnostico
     *
     * @param integer $puntajeDiagnostico
     */
    public function setPuntajeDiagnostico($puntajeDiagnostico)
    {
        $this->puntajeDiagnostico = $puntajeDiagnostico;
    }

    /**
     * Get puntajeDiagnostico
     *
     * @return integer
     */
    public function getPuntajeDiagnostico()
    {
        return $this->puntajeDiagnostico;
    }
    
    
    /**
     * Add areas
     *
     * @param Itsur\AeiBundle\Entity\Area $areas
     */
    public function addArea(Area $areas)
    {
        $this->areas[] = $areas;
    }

    /**
     * Get areas
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getAreas()
    {
        return $this->areas;
    }
}

?>

Entity/Pregunta.php
<?php

namespace Itsur\AeiBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Itsur\AeiBundle\Entity\Grupo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Itsur\AeiBundle\Entity\Pregunta
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Pregunta
{
    const IDENTIFICAR ='IDENTIFICAR';
    const CONOCER ='CONOCER';
    const DOMINAR='APLICAR';

    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var text $sentencia
     *
     * @ORM\Column(name="sentencia", type="text")
     */
    protected $sentencia;
    
    
    /**
     * @var string $objetivo
     *
     * @ORM\Column(name="objetivo", type="string", length=12)
     */
    protected $objetivo;
    
    /**
     *
     * @ORM\ManyToOne(targetEntity="Grupo",inversedBy="preguntas")
     * @ORM\JoinColumn(name="grupo_id", referencedColumnName="id")
     */
    protected $grupo;

    /**
     * @var string $imagen
     *
     * @ORM\Column(name="imagen", type="string", length=255, nullable=true)
     */
    protected $imagen;
    
    
    /**
     * @var string $respuestaImagenes
     *
     * @ORM\Column(name="respuestaImagenes", type="boolean", nullable=true)
     */
    protected $respuestaImagenes;
    
     /**
     * @var string $opcion1
     *
     * @ORM\Column(name="opcion1", type="text")
     */
    protected $opcion1;


    /**
     * @var string $opcion2
     *
     * @ORM\Column(name="opcion2", type="text")
     */
    protected $opcion2;


    /**
     * @var string $opcion3
     *
     * @ORM\Column(name="opcion3", type="text")
     */
    protected $opcion3;


    /**
     * @var string $opcion4
     *
     * @ORM\Column(name="opcion4", type="text")
     */
    protected $opcion4;


    /**
     * @var text $respuesta
     *
     * @ORM\Column(name="respuesta", type="text")
     * @Assert\Null()
     */
    protected $respuesta;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set sentencia
     *
     * @param text $sentencia
     */
    public function setSentencia($sentencia)
    {
        $this->sentencia = $sentencia;
    }

    /**
     * Get sentencia
     *
     * @return text 
     */
    public function getSentencia()
    {
        return $this->sentencia;
    }
    
    /**
     * Set objetivo
     *
     * @param string $objetivo
     */
    public function setObjetivo($objetivo)
    {
        $this->objetivo = $objetivo;
    }

    /**
     * Get objetivo
     *
     * @return string
     */
    public function getObjetivo()
    {
        return $this->objetivo;
    }

    /**
     * Set grupo
     *
     * @param Itsur\AeiBundle\Entity\Grupo $grupo
     */
    public function setGrupo(Grupo $grupo)
    {
        $this->grupo = $grupo;
    }

    /**
     * Get grupo
     *
     * @return Itsur\AeiBundle\Entity\Grupo 
     */
    public function getGrupo()
    {
        return $this->grupo;
    }

    /**
     * Set opcion1
     *
     * @param string $opcion1
     */
    public function setOpcion1($opcion1)
    {
        $this->opcion1 = $opcion1;
    }

    /**
     * Get opcion1
     *
     * @return string 
     */
    public function getOpcion1()
    {
        return $this->opcion1;
    }

    /**
     * Set opcion2
     *
     * @param string $opcion2
     */
    public function setOpcion2($opcion2)
    {
        $this->opcion2 = $opcion2;
    }

    /**
     * Get opcion2
     *
     * @return string 
     */
    public function getOpcion2()
    {
        return $this->opcion2;
    }

    /**
     * Set opcion3
     *
     * @param string $opcion3
     */
    public function setOpcion3($opcion3)
    {
        $this->opcion3 = $opcion3;
    }

    /**
     * Get opcion3
     *
     * @return string 
     */
    public function getOpcion3()
    {
        return $this->opcion3;
    }

    /**
     * Set opcion4
     *
     * @param string $opcion4
     */
    public function setOpcion4($opcion4)
    {
        $this->opcion4 = $opcion4;
    }

    /**
     * Get opcion4
     *
     * @return string 
     */
    public function getOpcion4()
    {
        return $this->opcion4;
    }

    /**
     * Set respuesta
     *
     * @param string $respuesta
     */
    public function setRespuesta($respuesta)
    {
        $this->respuesta = $respuesta;
    }

    /**
     * Get respuesta
     *
     * @return string 
     */
    public function getRespuesta()
    {
        return $this->respuesta;
    }
    
    /**
     * Set imagen
     *
     * @param string $imagen
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;
    }
    
    
    /**
     * Get imagen
     *
     * @return string
     */
    public function getImagen()
    {
        return $this->imagen;
    }
    
    /**
     * Set respuestaImagenes
     *
     * @param true $respuestaImagenes
     */
    public function setRespuestaImagenes($respuestaImagenes)
    {
        $this->respuestaImagenes = $respuestaImagenes;
    }
    
    
    /**
     * Get respuestImagenes
     *
     * @return true
     */
    public function getRespuetaImagenes()
    {
        return $this->respuestaImagenes;
    }
    
    /**
     * Recupera la puntuación de la pregunta
     *
     */
    public function getPuntaje(){
        $puntaje = 0;
         if($this->getObjetivo() == Pregunta::IDENTIFICAR){
          $puntaje = 1;
        }elseif($this->getObjetivo() == Pregunta::CONOCER){
          $puntaje = 2;
        }elseif($this->getObjetivo() == Pregunta::DOMINAR){
          $puntaje = 3;
        }
        return $puntaje;
    }
}

Form/ManualType.php
<?php

namespace Itsur\AeiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class ManualType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('clave')
            ->add('nombre')
            ->add('puntaje')
            ->add('puntajeSeleccion')
            ->add('puntajeDiagnostico')
        ;
    }

    public function getName()
    {
        return 'itsur_aeibundle_manualtype';
    }
}

Controller/ManualController.php
<?php

namespace Itsur\AeiBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Itsur\AeiBundle\Entity\Periodo;
use Itsur\AeiBundle\Entity\Manual;
use Itsur\AeiBundle\Form\PeriodoType;
use Itsur\AeiBundle\Entity\Utilerias;
use Itsur\AeiBundle\Form\ManualType;

/**
 * @Route("/admin/manual")
 * @Secure(roles="ROLE_ADMIN")
 */
class ManualController extends Controller
{

    
    /**
     * @Route("/show/{clave}", name="manual_show")
     * @Template()
     */
    public function showAction($clave)
    {
        
        $repository = $this->getDoctrine()->getRepository('ItsurAeiBundle:Manual');

        $manual =  $repository->findOneByClave($clave);

        return array(
                    'manual'=> $manual,
                );
    }


    /**
     * @Route("/actual", name="manual_actual")
     * @Template()
     */
    public function actualAction()
    {
        $manualActual = Utilerias::manualActual($this->getDoctrine());

        return $this->render('ItsurAeiBundle:Manual:show.html.twig',array(
            'manual'=> $manualActual,
        ));
    }

     /**
     * @Route("/list", name="manual_list")
     * @Template()
     */
    public function listAction()
    {
        $repository = $this->getDoctrine()->getRepository('ItsurAeiBundle:Manual');
        $manuales =  $repository->findAll();

        return $this->render('ItsurAeiBundle:Manual:list.html.twig',array(
        'manuales'=> $manuales,
        'noManuales'=>count($manuales),
        ));

    }


     /**
     * @Route("/grupospreguntas/{temaid}", name="manual_gruposPreguntas")
     * @Template()
     */
    public function gruposPreguntasAction($temaid)
    {
        $repository = $this->getDoctrine()->getRepository('ItsurAeiBundle:Tema');
        $tema =  $repository->findOneById($temaid);

        return array(
            'tema'=> $tema,
        );

    }
    

     /**
     *
     * @Route("/new", name="manual_new")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Manual();
        $form   = $this->createForm(new ManualType(), $entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView()
        );
    }

    /**
     * Creates a new Manual entity.
     *
     * @Route("/create", name="manual_create")
     * @Template("ItsurAeiBundle:Manual:new.html.twig")
     */
    public function createAction()
    {
        $entity  = new Manual();
        $request = $this->getRequest();
        $form    = $this->createForm(new ManualType(), $entity);
        $form->bindRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('manual_show', array('id' => $entity->getId())));
            
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView()
        );
    }

    /**
     * Displays a form to edit an existing Manual entity.
     *
     * @Route("/{id}/edit", name="manual_edit")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('ItsurAeiBundle:Manual')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Manual entity.');
        }

        $editForm = $this->createForm(new ManualType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edits an existing Manual entity.
     *
     * @Route("/{id}/update", name="manual_update")
     * @Template("ItsurAeiBundle:Manual:edit.html.twig")
     */
    public function updateAction($id)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('ItsurAeiBundle:Manual')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Manual entity.');
        }

        $editForm   = $this->createForm(new ManualType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        $request = $this->getRequest();

        $editForm->bindRequest($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('manual_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a Manual entity.
     *
     * @Route("/{id}/delete", name="manual_delete")

     */
    public function deleteAction($id)
    {
        $form = $this->createDeleteForm($id);
        $request = $this->getRequest();

        $form->bindRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();
            $entity = $em->getRepository('ItsurAeiBundle:Manual')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Manual entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('manual'));
    }

    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(array('id' => $id))
            ->add('id', 'hidden')
            ->getForm()
        ;
    }
    
        
        
    
}

















Resources/views/Manual/edit.html.twig
<h1>Manual edit</h1>

<form action="{{ path('manual_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
    {{ form_widget(edit_form) }}
    <p>
        <button type="submit">Edit</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('manual') }}">
            Back to the list
        </a>
    </li>
    <li>
        <form action="{{ path('manual_delete', { 'id': entity.id }) }}" method="post">
            {{ form_widget(delete_form) }}
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>

Resources/views/Manual/grupospreguntas.html.twig
{% extends 'ItsurAeiBundle::layout.html.twig' %}
{% block title %}
    Mostrar Manual
{% endblock %}

{% block body %}
   <h1>Tema</h1> 
    <br/>
    Puntaje: {{tema.nombre}}
    <br/>
    Puntaje: {{tema.puntaje}}
    <br/>
    Cantidad de grupos: {{tema.grupos.count}}
    <br/>
    Grupos
    <br/>
    <br/>
    {% for grupo in tema.grupos %}
        <br/>
        Puntaje: {{grupo.puntaje}}
        <br/>
        Instrucciones: {{grupo.instrucciones}}
        <br/>
        Caso: {{grupo.caso}}
        <br/>
        Cantidad de preguntas: {{grupo.cantidadPreguntas}}
        <br/>
        Preguntas
        <br/>
        <br/>
        {% for pregunta in grupo.preguntas %}
           Sentencia: {{pregunta.sentencia}}
           <br/>
           Objetivo: {{pregunta.objetivo}}
           <br/>
           Imagen: {{pregunta.imagen}}
           <br/>
           <br/>
           imagen de respuesta?: {{pregunta.respuetaImagenes}}
           <br/>
           Opción 1: {{pregunta.opcion1}}
           <br/>
           Opción 2: {{pregunta.opcion2}}
           <br/>
           Opción 3: {{pregunta.opcion3}}
           <br/>
           Opción 4: {{pregunta.opcion4}}
           <br/>
           Respuesta 4: {{pregunta.respuesta}}
           <br/>
        {% endfor %}
        <br/>
    {% endfor %}

{% endblock %}

Resources/views/Manual/index.html.twig
<h1>Manual list</h1>

<table class="records_list">
    <thead>
        <tr>
            <th>Id</th>
            <th>Clave</th>
            <th>Nombre</th>
            <th>Puntaje</th>
            <th>Puntajeseleccion</th>
            <th>Puntajediagnostico</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        <tr>
            <td><a href="{{ path('manual_show', { 'id': entity.id }) }}">{{ entity.id }}</a></td>
            <td>{{ entity.clave }}</td>
            <td>{{ entity.nombre }}</td>
            <td>{{ entity.puntaje }}</td>
            <td>{{ entity.puntajeSeleccion }}</td>
            <td>{{ entity.puntajeDiagnostico }}</td>
            <td>
                <ul>
                    <li>
                        <a href="{{ path('manual_show', { 'id': entity.id }) }}">show</a>
                    </li>
                    <li>
                        <a href="{{ path('manual_edit', { 'id': entity.id }) }}">edit</a>
                    </li>
                </ul>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<ul>
    <li>
        <a href="{{ path('manual_new') }}">
            Create a new entry
        </a>
    </li>
</ul>

Resources/views/Manual/new.html.twig
<h1>Nuevo manual</h1>

<form action="{{ path('manual_create') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <p>
        <button type="submit">Agregar</button>
    </p>
</form>

<ul class="record_actions">
    <li>
        <a href="{{ path('manual_list') }}">
            Regresar
        </a>
    </li>
</ul>

Resources/views/Manual/show.html.twig
{% extends 'ItsurAeiBundle::layout.html.twig' %}
{% block title %}
    Mostrar Manual
{% endblock %}

{% block body %}
   <h1>Información del Manual</h1> 
    <br/>
    Clave: {{manual.clave}}
    <br/>
    Nombre: {{manual.nombre}}
    <br/>
    Puntaje Total: {{manual.puntaje}}
    <br/>
    Puntaje de Selección: {{manual.puntajeSeleccion}}
    <br/>
    Puntaje de Diagnostico: {{manual.puntajeDiagnostico}}
    <br/>
    <br/>
    Areas
    <br/>
    <br/>
    {% for area in manual.areas %}
        Area: {{area.nombre}}
        <br/>
        {% for seccion in area.secciones %}
           Sección: {{seccion.nombre}}
           <br/>
           {% for tema in seccion.temas %}
                Tema: {{tema.nombre}}  <td> <a href="{{path('manual_gruposPreguntas',{'temaid':tema.id} ) }}">A</a> </td>
                <br/>
            {% endfor %}

        {% endfor %}
        <br/>
    {% endfor %}

{% endblock %}